DROP INDEX IF EXISTS  metabib.metabib_author_field_entry_index_vector_idx;
DROP INDEX IF EXISTS  metabib.metabib_author_field_entry_source_idx;
DROP INDEX IF EXISTS  metabib.metabib_author_field_entry_value_idx;
DROP INDEX IF EXISTS  metabib.metabib_keyword_field_entry_index_vector_idx;
DROP INDEX IF EXISTS  metabib.metabib_keyword_field_entry_source_idx;
DROP INDEX IF EXISTS  metabib.metabib_keyword_field_entry_value_idx;
DROP INDEX IF EXISTS  metabib."fki_normalized_author_to_ author_field_entry_FK";
DROP INDEX IF EXISTS  metabib.normalized_author_field_entry_gist_trgm;
DROP INDEX IF EXISTS  metabib.normalized_remove_insignificants_author_field_entry_gist_trgm;
DROP INDEX IF EXISTS  metabib."fki_normalized_keyword_to_ keyword_field_entry_FK";
DROP INDEX IF EXISTS  metabib."fki_normalized_series_to_ series_field_entry_FK";
DROP INDEX IF EXISTS  metabib.normalized_remove_insignificants_series_field_entry_gist_trgm;
DROP INDEX IF EXISTS  metabib.normalized_series_field_entry_gist_trgm;
DROP INDEX IF EXISTS  metabib."fki_normalized_subject_to_ subject_field_entry_FK";
DROP INDEX IF EXISTS  metabib.normalized_remove_insignificants_subject_field_entry_gist_trgm;
DROP INDEX IF EXISTS  metabib.normalized_subject_field_entry_gist_trgm;
DROP INDEX IF EXISTS  metabib."fki_normalized_title_to_ title_field_entry_FK";
DROP INDEX IF EXISTS  metabib.normalized_remove_insignificants_title_field_entry_gist_trgm;
DROP INDEX IF EXISTS  metabib.normalized_title_field_entry_gist_trgm;
DROP INDEX IF EXISTS  metabib.metabib_subject_field_entry_index_vector_idx;
DROP INDEX IF EXISTS  metabib.metabib_subject_field_entry_source_idx;
DROP INDEX IF EXISTS  metabib.metabib_subject_field_entry_value_idx;
DROP INDEX IF EXISTS  metabib.metabib_title_field_entry_index_vector_idx;
DROP INDEX IF EXISTS  metabib.metabib_title_field_entry_source_idx;
DROP INDEX IF EXISTS  metabib.metabib_title_field_entry_value_idx;
DROP INDEX IF EXISTS  metabib.metabib_series_field_entry_index_vector_idx;
DROP INDEX IF EXISTS  metabib.metabib_series_field_entry_source_idx;
DROP INDEX IF EXISTS  metabib.metabib_series_field_entry_value_idx;
